version: '3.8'
services:
  front:
    image: node:21.2.0
    container_name: front
    volumes:
      - ./front:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run ${VUEJS_OPTION}"
  back:
    container_name: back
    build:     
      context: .
      dockerfile: docker/back/Dockerfile
    volumes:
      - ./docker/back/config.json:/root/config.json
      - ./back:/app
    ports: 
        - 8080:8080
    depends_on:
      - mysql
    command: ["go", "run", "cmd/main.go", "-config", "/root/config.json"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/dump/mysql/:/root/dump/
      - mysql:/var/lib/mysql   

volumes:
  mysql:
